"""scribectl — the command surface.

core/ takes the vault as data and never writes. This module is the only place
that holds write paths, and they are exactly the designated outputs:
pack_output/ (pack), control/Status.md (status --write), ledger appends
(ratify), stubs (adopt, init). Nothing here rewrites a note a human edits.
"""
from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

from .config import DEFAULTS, DEFAULT_ROOTS, ProjectConfig, discover_projects, vault_roots
from .core.contextpack import build_pack
from .core.project import project as project_rows
from .core.vault import Vault

TEMPLATES = Path(__file__).parent / "templates"


class CLIError(Exception):
    pass


# -- project selection --------------------------------------------------------

def _select(name: str | None = None, card: str | None = None) -> ProjectConfig:
    """Resolve -p by name; else infer from cwd, then from where the card
    resolves, then fall back to the only project there is."""
    projects = discover_projects()
    if name:
        for p in projects:
            if p.name == name:
                return p
        raise CLIError(f"no project named {name!r} (known: {', '.join(p.name for p in projects) or 'none'})")
    if not projects:
        raise CLIError("no projects found under " + ", ".join(map(str, vault_roots())))
    cwd = Path.cwd()
    inside = [p for p in projects if p.root == cwd or p.root in cwd.parents]
    if len(inside) == 1:
        return inside[0]
    if card:
        holding = [p for p in projects
                   if (n := Vault.load(p.root).resolve(card)) and n.type == "scene_card"]
        if len(holding) == 1:
            return holding[0]
    if len(projects) == 1:
        return projects[0]
    raise CLIError("ambiguous project; pass -p (" + ", ".join(p.name for p in projects) + ")")


# -- commands ------------------------------------------------------------------

def cmd_projects(args) -> int:
    projects = discover_projects()
    if not projects:
        print("no projects found under " + ", ".join(map(str, vault_roots())))
        return 0
    w = max(len(p.name) for p in projects)
    for p in projects:
        print(f"{p.name:<{w}}  {p.template_set:<8}  {p.root}")
    return 0


def _status_table(rows) -> str:
    w = max((len(n) for _, n, _ in rows), default=10)
    lines = [f"{'type':<12} {'name':<{w}} status", "-" * (14 + w + 8)]
    lines += [f"{t:<12} {n:<{w}} {s}" for t, n, s in rows]
    return "\n".join(lines)


def cmd_status(args) -> int:
    cfg = _select(args.project)
    rows = project_rows(Vault.load(cfg.root))
    print(_status_table(rows))
    if args.write:
        dash = cfg.roots["control"] / "Status.md"
        body = [
            "---", "type: status_dashboard", "---", "",
            f"# Status — {cfg.name}", "",
            f"_Generated by `scribectl status --write` on {date.today().isoformat()}. "
            "A cache: regenerated every run, read back by nothing. "
            "Do not edit — edit the vault._", "",
            "| type | name | status |", "| --- | --- | --- |",
        ]
        body += [f"| {t} | {n} | {s} |" for t, n, s in rows]
        dash.parent.mkdir(parents=True, exist_ok=True)
        dash.write_text("\n".join(body) + "\n", encoding="utf-8")
        print(f"\nwrote {dash}")
    return 0


def cmd_pack(args) -> int:
    cfg = _select(args.project, card=args.card)
    try:
        pack = build_pack(Vault.load(cfg.root), args.card)
    except ValueError as e:
        raise CLIError(str(e)) from e
    cfg.pack_output.mkdir(parents=True, exist_ok=True)
    out = cfg.pack_output / f"{args.card.replace(' ', '-')}-context.md"
    out.write_text(pack.markdown, encoding="utf-8")
    print(f"wrote {out}  (sha {pack.sha}, {len(pack.markdown)} bytes)")
    return 0


def cmd_ratify(args) -> int:
    cfg = _select(args.project)
    groups = [("Accepted", args.accept), ("Rejected", args.reject), ("Deferred", args.defer)]
    if not any(entries for _, entries in groups):
        raise CLIError("nothing to ratify: pass --accept/--reject/--defer at least once")
    ledger = cfg.ratification_log
    if not ledger.is_file():
        raise CLIError(f"ratification log missing: {ledger}")
    block = [f"\n## {date.today().isoformat()}"]
    for title, entries in groups:
        if entries:
            block.append(f"\n### {title}")
            block += [f"- {e}" for e in entries]
    existing = ledger.read_text(encoding="utf-8")
    lead = "" if existing.endswith("\n") else "\n"
    with ledger.open("a", encoding="utf-8") as f:  # append-only: the sole writer
        f.write(lead + "\n".join(block) + "\n")
    n = sum(len(e) for _, e in groups)
    print(f"appended {n} entr{'y' if n == 1 else 'ies'} to {ledger}")
    return 0


ADOPT_STUB = """\
---
type: canon_node
domain: unclassified
importance: supporting
source: "[[{name}]]"
adopted: {today}
---

# {name}

## One-line function
_(unratified — adopted from [[{name}]]; write this once the node earns a job)_

## Ratified facts
_(none ratified yet — node is a stub)_

## Open questions
- Which claims in [[{name}]] survive contact with existing canon?
- What in the source is load-bearing enough to ratify first?

## Story utility
Discover-mode wrapper around the legacy source [[{name}]]. Extract facts by
hand; ratify them with `scribectl ratify` — the log is the receipt.
"""


def cmd_adopt(args) -> int:
    cfg = _select(args.project)
    src = Path(args.note)
    if not (src.is_file() and src.suffix == ".md"):
        hits = [p for root in vault_roots() if root.is_dir()
                for p in root.rglob(f"{args.note}.md")]
        if not hits:
            raise CLIError(f"no note named {args.note!r} under " + ", ".join(map(str, vault_roots())))
        src = hits[0]
    name = src.stem
    stub = cfg.roots["world"] / "canon" / f"{name}.md"
    if stub.exists():
        raise CLIError(f"refusing to overwrite existing note: {stub}")
    stub.parent.mkdir(parents=True, exist_ok=True)
    stub.write_text(ADOPT_STUB.format(name=name, today=date.today().isoformat()), encoding="utf-8")
    print(f"adopted {src} → {stub} (stub with open questions; source untouched)")
    return 0


PROJECT_NOTE = """\
---
type: scribe-project
name: {name}
template_set: {template_set}
roots:
{roots}
voice_canon: {voice_canon}
timeline: {timeline}
ratification_log: {ratification_log}
pack_output: {pack_output}
sources: []
---

Project notes go here — scribectl reads only the frontmatter above.
List legacy vault notes under `sources:` to mark them citable ore.
"""

# template file in the set → where it lands in a fresh project
INIT_LEDGERS = {
    "timeline.md": "control/timeline/Timeline.md",
    "ratification_log.md": "control/ratification/Ratification Log.md",
    "voice_canon.md": "world/language/Prose Voice Canon.md",
    "world_seed.md": "world/World Seed.md",
}
INIT_DIRS = [
    "world/canon", "world/language", "structure/scenes", "body/drafts",
    "control/timeline", "control/ratification", "control/context-packs",
    "reviews/canon", "reviews/voice", "reviews/beta",
]


def cmd_init(args) -> int:
    tset = TEMPLATES / args.set
    if not tset.is_dir():
        known = ", ".join(sorted(p.name for p in TEMPLATES.iterdir() if p.is_dir()))
        raise CLIError(f"unknown template set {args.set!r} (available: {known})")
    under = Path(args.under) if args.under else vault_roots()[0] / "30 Creative" / "Works"
    dest = under / args.name
    if dest.exists():
        raise CLIError(f"refusing to touch existing directory: {dest}")
    for d in INIT_DIRS:
        (dest / d).mkdir(parents=True)
    for src, rel in INIT_LEDGERS.items():
        (dest / rel).write_text((tset / src).read_text(encoding="utf-8"), encoding="utf-8")
    note = dest / f"{args.name}.md"
    roots_yaml = "\n".join(f"  {k}: {v}" for k, v in DEFAULT_ROOTS.items())
    fields = {**DEFAULTS, "name": args.name, "template_set": args.set, "roots": roots_yaml}
    note.write_text(PROJECT_NOTE.format(**fields), encoding="utf-8")
    print(f"initialized {args.name} at {dest}")
    return 0


# -- entry ---------------------------------------------------------------------

def _parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(prog="scribectl",
                                 description="contract runner for vault-resident writing projects")
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("projects", help="list discovered projects").set_defaults(fn=cmd_projects)

    p = sub.add_parser("status", help="derived state of every node + card")
    p.add_argument("-p", "--project")
    p.add_argument("--write", action="store_true", help="also emit control/Status.md")
    p.set_defaults(fn=cmd_status)

    p = sub.add_parser("pack", help="assemble + freeze a hashed context pack")
    p.add_argument("card")
    p.add_argument("-p", "--project")
    p.set_defaults(fn=cmd_pack)

    p = sub.add_parser("ratify", help="append invention verdicts to the ratification log")
    p.add_argument("-p", "--project")
    p.add_argument("--accept", action="append", default=[], metavar="ENTRY")
    p.add_argument("--reject", action="append", default=[], metavar="ENTRY")
    p.add_argument("--defer", action="append", default=[], metavar="ENTRY")
    p.set_defaults(fn=cmd_ratify)

    p = sub.add_parser("adopt", help="wrap a legacy vault note as a canon-node stub")
    p.add_argument("note", help="note name (searched under vault roots) or path")
    p.add_argument("-p", "--project")
    p.set_defaults(fn=cmd_adopt)

    p = sub.add_parser("init", help="instantiate a project subtree + scribe-project note")
    p.add_argument("name")
    p.add_argument("--set", default="fiction", help="template set (default: fiction)")
    p.add_argument("--under", help="parent directory (default: <vault>/30 Creative/Works)")
    p.set_defaults(fn=cmd_init)
    return ap


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        return args.fn(args)
    except CLIError as e:
        print(f"scribectl: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
