"""scribectl — the command surface.

core/ takes the vault as data and never writes. This module is the only place
that holds write paths, and they are exactly the designated outputs:
pack_output/ (pack), control/Status.md (status --write), ledger appends
(ratify), stubs (adopt, init), the verdict inbox (ratify --sweep clears
decided candidates), and — the one sanctioned append into a human note — a
swept fact landing in its node's `## Ratified facts`. That write is the
writer's own verdict executed: append-only, into exactly one section,
receipt-logged, byte-traceable to a checkbox the writer ticked
(docs/RATIFICATION.md, "the write-discipline question"). Nothing here ever
rewrites what a human wrote.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

from .config import DEFAULTS, DEFAULT_ROOTS, ProjectConfig, discover_projects, vault_roots
from .core.contextpack import build_pack
from .core.inbox import append_bullets, mine, parse_inbox, receipt, remove_candidates
from .core.project import card_artifacts, project as project_rows
from .core.vault import Vault
from .templateset import TemplateSet, list_sets, load_set


class CLIError(Exception):
    pass


def _ts(cfg: ProjectConfig) -> TemplateSet:
    try:
        return load_set(cfg.template_set)
    except ValueError as e:
        raise CLIError(f"{cfg.name}: {e}") from e


# -- project selection --------------------------------------------------------

def _select(name: str | None = None, card: str | None = None) -> ProjectConfig:
    """Resolve -p by name; else infer from cwd, then from where the card
    resolves, then fall back to the only project there is."""
    projects = discover_projects()
    if name:
        for p in projects:
            if p.name == name:
                return p
        raise CLIError(f"no project named {name!r} (known: {', '.join(p.name for p in projects) or 'none'})")
    if not projects:
        raise CLIError("no projects found under " + ", ".join(map(str, vault_roots())))
    cwd = Path.cwd()
    inside = [p for p in projects if p.root == cwd or p.root in cwd.parents]
    if len(inside) == 1:
        return inside[0]
    if card:
        holding = [p for p in projects
                   if (n := Vault.load(p.root).resolve(card)) and n.type == _ts(p).card_type]
        if len(holding) == 1:
            return holding[0]
    if len(projects) == 1:
        return projects[0]
    raise CLIError("ambiguous project; pass -p (" + ", ".join(p.name for p in projects) + ")")


# -- commands ------------------------------------------------------------------

def cmd_projects(args) -> int:
    projects = discover_projects()
    if not projects:
        print("no projects found under " + ", ".join(map(str, vault_roots())))
        return 0
    w = max(len(p.name) for p in projects)
    for p in projects:
        print(f"{p.name:<{w}}  {p.template_set:<8}  {p.root}")
    return 0


def _status_table(rows) -> str:
    w = max((len(n) for _, n, _, _ in rows), default=10)
    tw = max([len(t) for t, _, _, _ in rows] + [12])
    lines = [f"{'type':<{tw}} {'name':<{w}} status", "-" * (tw + 2 + w + 8)]
    lines += [f"{t:<{tw}} {n:<{w}} {s}" + (f"  ({d})" if d else "") for t, n, s, d in rows]
    return "\n".join(lines)


def _status_json(cfg: ProjectConfig, vault: Vault, ts: TemplateSet, rows) -> str:
    """Machine-readable derived state — the dispatch layer's entire view of a
    project (docs/DISPATCH.md). Paths are absolute; card rows carry their
    drafts and reviews-by-kind so the dispatcher never re-derives state."""
    out = {
        "project": {
            "name": cfg.name,
            "root": str(cfg.root),
            "template_set": cfg.template_set,
            "card_type": ts.card_type,
            "paths": {
                "voice_canon": str(cfg.voice_canon),
                "timeline": str(cfg.timeline),
                "ratification_log": str(cfg.ratification_log),
                "ratification_inbox": str(cfg.ratification_inbox),
                "pack_output": str(cfg.pack_output),
                "roots": {k: str(v) for k, v in cfg.roots.items()},
            },
        },
        "rows": [],
    }
    for t, n, s, d in rows:
        row = {"type": t, "name": n, "status": s, "detail": d}
        if t == ts.card_type:
            row.update(card_artifacts(vault, n))
        out["rows"].append(row)
    return json.dumps(out, ensure_ascii=False, indent=2)


def cmd_status(args) -> int:
    cfg = _select(args.project)
    vault = Vault.load(cfg.root)
    ts = _ts(cfg)
    rows = project_rows(vault, ts)
    if args.json:
        print(_status_json(cfg, vault, ts, rows))
    else:
        print(_status_table(rows))
    if args.write:
        dash = cfg.roots["control"] / "Status.md"
        body = [
            "---", "type: status_dashboard", "---", "",
            f"# Status — {cfg.name}", "",
            f"_Generated by `scribectl status --write` on {date.today().isoformat()}. "
            "A cache: regenerated every run, read back by nothing. "
            "Do not edit — edit the vault._", "",
            "| type | name | status | detail |", "| --- | --- | --- | --- |",
        ]
        body += [f"| {t} | {n} | {s} | {d} |" for t, n, s, d in rows]
        dash.parent.mkdir(parents=True, exist_ok=True)
        dash.write_text("\n".join(body) + "\n", encoding="utf-8")
        print(f"\nwrote {dash}")
    return 0


def cmd_pack(args) -> int:
    cfg = _select(args.project, card=args.card)
    try:
        pack = build_pack(Vault.load(cfg.root), args.card, _ts(cfg))
    except ValueError as e:
        raise CLIError(str(e)) from e
    cfg.pack_output.mkdir(parents=True, exist_ok=True)
    # The sha is in the filename so a regenerated pack never clobbers the
    # frozen pack an earlier draft cites — freeze-to-audit survives iteration.
    out = cfg.pack_output / f"{args.card.replace(' ', '-')}-{pack.sha}-context.md"
    if out.exists():
        print(f"unchanged {out}  (sha {pack.sha} already frozen)")
    else:
        out.write_text(pack.markdown, encoding="utf-8")
        print(f"wrote {out}  (sha {pack.sha}, {len(pack.markdown)} bytes)")
    for warn in pack.warnings:
        print(f"scribectl: warning: {warn}", file=sys.stderr)
    return 0


def _append_ledger(ledger: Path, groups: list[tuple[str, list[str]]]) -> int:
    """Append one dated block of verdict entries; returns the entry count."""
    if not ledger.is_file():
        raise CLIError(f"ratification log missing: {ledger}")
    existing = ledger.read_text(encoding="utf-8")
    today = date.today().isoformat()
    date_headings = [l.strip()[3:].strip() for l in existing.splitlines()
                     if l.startswith("## ")]
    # Reuse today's block if it is already the ledger's last date heading;
    # still append-only — we only skip emitting a duplicate heading.
    block = [] if date_headings and date_headings[-1] == today else [f"\n## {today}"]
    for title, entries in groups:
        if entries:
            block.append(f"\n### {title}")
            block += [f"- {e}" for e in entries]
    lead = "" if existing.endswith("\n") else "\n"
    with ledger.open("a", encoding="utf-8") as f:  # append-only: the sole writer
        f.write(lead + "\n".join(block) + "\n")
    return sum(len(e) for _, e in groups)


def _mine(cfg: ProjectConfig, dry_run: bool, standalone: bool = False) -> int:
    """Queue review-report candidates into the inbox as pending (mining is
    mechanics: only the writer's checkbox ever decides). Creates the inbox
    from the set's template on first use — mining is what first proposes
    canon. Idempotent: a report wikilinked from inbox or ledger is skipped."""
    vault = Vault.load(cfg.root)
    inbox = cfg.ratification_inbox
    base = inbox.read_text(encoding="utf-8") if inbox.is_file() \
        else (_ts(cfg).dir / "ratification_inbox.md").read_text(encoding="utf-8")
    ledger = cfg.ratification_log
    ledger_text = ledger.read_text(encoding="utf-8") if ledger.is_file() else ""
    blocks, names = mine(vault, base, ledger_text)
    if not blocks:
        if standalone:
            print("nothing to mine (no unqueued review-report candidates)")
        return 0
    what = (f"{len(blocks)} candidate{'s' if len(blocks) != 1 else ''} from "
            f"{len(names)} review report{'s' if len(names) != 1 else ''}")
    if dry_run:
        print(f"dry run — would queue {what} into {inbox.name}:\n")
        print("\n".join(blocks) + "\n")
        return 0
    inbox.parent.mkdir(parents=True, exist_ok=True)
    lead = base if base.endswith("\n") else base + "\n"
    inbox.write_text(lead + "\n".join(blocks) + "\n", encoding="utf-8")
    print(f"queued {what} into {inbox.name}")
    return 0


def _sweep(cfg: ProjectConfig, dry_run: bool) -> int:
    """Execute the writer's checkbox verdicts from the inbox: fact into the
    node, receipt into the ledger, candidate out of the inbox — the mechanics
    of ratification with the decision already made (docs/RATIFICATION.md)."""
    inbox = cfg.ratification_inbox
    if not inbox.is_file():
        raise CLIError(f"no inbox at {inbox} — nothing has proposed canon yet "
                       "(the ratification_inbox template creates it)")
    text = inbox.read_text(encoding="utf-8")
    candidates, problems = parse_inbox(text)
    for lineno, msg in problems:
        print(f"scribectl: warning: {inbox.name}:{lineno}: {msg}", file=sys.stderr)
    decided = [c for c in candidates if c.verdict != "pending"]
    pending = len(candidates) - len(decided)
    if not decided:
        print(f"nothing to sweep ({pending} pending candidate{'s' if pending != 1 else ''} in {inbox.name})")
        return 0

    # Validate every accept before writing anything: a fact with no node to
    # land in must keep its checkbox, not lose it to a half-executed sweep.
    vault = Vault.load(cfg.root)
    ts = _ts(cfg)
    ok: list = []
    for c in decided:
        node = vault.resolve(c.target)
        if c.verdict == "accept" and node is None:
            print(f"scribectl: warning: [[{c.target}]] does not resolve — "
                  f"candidate stays in the inbox", file=sys.stderr)
        elif c.verdict == "accept" and node.type not in ts.node_types:
            print(f"scribectl: warning: [[{c.target}]] is {node.type}, not a fact-bearing "
                  f"node ({', '.join(ts.node_types)}) — candidate stays in the inbox", file=sys.stderr)
        else:
            ok.append(c)

    by_node: dict[str, list] = {}
    for c in ok:
        if c.verdict == "accept":
            by_node.setdefault(c.target, []).append(c)

    if dry_run:
        print("dry run — nothing written\n")
        for target, cs in by_node.items():
            print(f"would append to [[{target}]] · Ratified facts:")
            for c in cs:
                print(f"  - {c.fact}")
        for title, v in (("Accepted", "accept"), ("Rejected", "reject"), ("Deferred", "defer")):
            for c in ok:
                if c.verdict == v:
                    print(f"would ledger under {title}: - {receipt(c)}")
        print(f"\nwould clear {len(ok)} candidate{'s' if len(ok) != 1 else ''} from {inbox.name}; {pending} pending would remain")
        return 0

    for target, cs in by_node.items():
        node = vault.resolve(target)
        try:
            new = append_bullets(node.path.read_text(encoding="utf-8"),
                                 "Ratified facts", [c.fact for c in cs])
        except ValueError as e:
            print(f"scribectl: warning: [[{target}]]: {e} — "
                  f"candidate stays in the inbox", file=sys.stderr)
            ok = [c for c in ok if c.target != target or c.verdict != "accept"]
            continue
        node.path.write_text(new, encoding="utf-8")
        print(f"ratified {len(cs)} fact{'s' if len(cs) != 1 else ''} into [[{target}]]")
    groups = [(title, [receipt(c) for c in ok if c.verdict == v])
              for title, v in (("Accepted", "accept"), ("Rejected", "reject"), ("Deferred", "defer"))]
    if ok:
        n = _append_ledger(cfg.ratification_log, groups)
        print(f"appended {n} receipt{'s' if n != 1 else ''} to {cfg.ratification_log.name}")
        inbox.write_text(remove_candidates(text, ok), encoding="utf-8")
    print(f"cleared {len(ok)} candidate{'s' if len(ok) != 1 else ''} from {inbox.name}; {pending} pending remain")
    return 0


def cmd_ratify(args) -> int:
    cfg = _select(args.project)
    groups = [("Accepted", args.accept), ("Rejected", args.reject), ("Deferred", args.defer)]
    if args.sweep or args.mine:
        if any(entries for _, entries in groups):
            raise CLIError("--sweep/--mine take their candidates from reports and the inbox; "
                           "drop --accept/--reject/--defer")
        if not args.sweep:
            return _mine(cfg, dry_run=args.dry_run, standalone=True)
        # Sweep lifts fresh report candidates first (they land pending, so the
        # writer's next look has them), then executes the decided ones.
        _mine(cfg, dry_run=args.dry_run)
        return _sweep(cfg, dry_run=args.dry_run)
    if args.dry_run:
        raise CLIError("--dry-run only applies to --sweep/--mine")
    if not any(entries for _, entries in groups):
        raise CLIError("nothing to ratify: pass --accept/--reject/--defer at least once, or --sweep")
    n = _append_ledger(cfg.ratification_log, groups)
    print(f"appended {n} entr{'y' if n == 1 else 'ies'} to {cfg.ratification_log}")
    return 0


ADOPT_STUB = """\
---
type: canon_node
domain: unclassified
importance: supporting
source: "[[{name}]]"
adopted: {today}
---

# {name}

## One-line function
_(unratified — adopted from [[{name}]]; write this once the node earns a job)_

## Ratified facts
_(none ratified yet — node is a stub)_

## Open questions
- Which claims in [[{name}]] survive contact with existing canon?
- What in the source is load-bearing enough to ratify first?

## Story utility
Discover-mode wrapper around the legacy source [[{name}]]. Extract facts by
hand; ratify them with `scribectl ratify` — the log is the receipt.
"""


def cmd_adopt(args) -> int:
    cfg = _select(args.project)
    src = Path(args.note)
    if not (src.is_file() and src.suffix == ".md"):
        hits = [p for root in vault_roots() if root.is_dir()
                for p in root.rglob(f"{args.note}.md")]
        if not hits:
            raise CLIError(f"no note named {args.note!r} under " + ", ".join(map(str, vault_roots())))
        src = hits[0]
    name = src.stem
    stub = cfg.roots["world"] / "canon" / f"{name}.md"
    if stub.exists():
        raise CLIError(f"refusing to overwrite existing note: {stub}")
    stub.parent.mkdir(parents=True, exist_ok=True)
    stub.write_text(ADOPT_STUB.format(name=name, today=date.today().isoformat()), encoding="utf-8")
    print(f"adopted {src} → {stub} (stub with open questions; source untouched)")
    return 0


PROJECT_NOTE = """\
---
type: scribe-project
name: {name}
template_set: {template_set}
roots:
{roots}
voice_canon: {voice_canon}
timeline: {timeline}
ratification_log: {ratification_log}
ratification_inbox: {ratification_inbox}
pack_output: {pack_output}
sources: []
---

Project notes go here — scribectl reads only the frontmatter above.
List legacy vault notes under `sources:` to mark them citable ore.
"""

def cmd_init(args) -> int:
    # Which dirs exist and which ledger templates get instantiated is the
    # template set's manifest, not this module's opinion.
    try:
        ts = load_set(args.set)
    except ValueError as e:
        raise CLIError(str(e)) from e
    under = Path(args.under) if args.under else vault_roots()[0] / "30 Creative" / "Works"
    dest = under / args.name
    if dest.exists():
        raise CLIError(f"refusing to touch existing directory: {dest}")
    for d in ts.init_dirs:
        (dest / d).mkdir(parents=True)
    for src, rel in ts.init_files.items():
        (dest / rel).write_text((ts.dir / src).read_text(encoding="utf-8"), encoding="utf-8")
    note = dest / f"{args.name}.md"
    roots_yaml = "\n".join(f"  {k}: {v}" for k, v in DEFAULT_ROOTS.items())
    fields = {**DEFAULTS, "name": args.name, "template_set": args.set, "roots": roots_yaml}
    note.write_text(PROJECT_NOTE.format(**fields), encoding="utf-8")
    print(f"initialized {args.name} at {dest}")
    return 0


# -- entry ---------------------------------------------------------------------

def _parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(prog="scribectl",
                                 description="contract runner for vault-resident writing projects")
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("projects", help="list discovered projects").set_defaults(fn=cmd_projects)

    p = sub.add_parser("status", help="derived state of every node + card")
    p.add_argument("-p", "--project")
    p.add_argument("--write", action="store_true", help="also emit control/Status.md")
    p.add_argument("--json", action="store_true",
                   help="machine-readable state: project header + rows with per-card drafts/reviews")
    p.set_defaults(fn=cmd_status)

    p = sub.add_parser("pack", help="assemble + freeze a hashed context pack")
    p.add_argument("card")
    p.add_argument("-p", "--project")
    p.set_defaults(fn=cmd_pack)

    p = sub.add_parser("ratify", help="append invention verdicts to the ratification log")
    p.add_argument("-p", "--project")
    p.add_argument("--accept", action="append", default=[], metavar="ENTRY")
    p.add_argument("--reject", action="append", default=[], metavar="ENTRY")
    p.add_argument("--defer", action="append", default=[], metavar="ENTRY")
    p.add_argument("--sweep", action="store_true",
                   help="execute the checkbox verdicts in the ratification inbox "
                        "(mines new review-report candidates first)")
    p.add_argument("--mine", action="store_true",
                   help="queue review-report 'Introduced candidates' into the inbox as pending")
    p.add_argument("--dry-run", action="store_true",
                   help="with --sweep/--mine: print what would land where, write nothing")
    p.set_defaults(fn=cmd_ratify)

    p = sub.add_parser("adopt", help="wrap a legacy vault note as a canon-node stub")
    p.add_argument("note", help="note name (searched under vault roots) or path")
    p.add_argument("-p", "--project")
    p.set_defaults(fn=cmd_adopt)

    p = sub.add_parser("init", help="instantiate a project subtree + scribe-project note")
    p.add_argument("name")
    p.add_argument("--set", default="fiction",
                   help=f"template set (default: fiction; available: {', '.join(list_sets())})")
    p.add_argument("--under", help="parent directory (default: <vault>/30 Creative/Works)")
    p.set_defaults(fn=cmd_init)
    return ap


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        return args.fn(args)
    except CLIError as e:
        print(f"scribectl: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
